// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqZAtobAWoK3m5R_Zo3leGVqid_aUzwh0',
    appId: '1:145240505070:web:10a64248412c28fcd8d1ff',
    messagingSenderId: '145240505070',
    projectId: 'mealbuddy-e829c',
    authDomain: 'mealbuddy-e829c.firebaseapp.com',
    databaseURL: 'https://mealbuddy-e829c-default-rtdb.firebaseio.com',
    storageBucket: 'mealbuddy-e829c.appspot.com',
    measurementId: 'G-XF841NV28L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09mQOfkgvaXEjiKIGaDJy44YLm8YhOEI',
    appId: '1:145240505070:android:6a9e5e6dd255b0b5d8d1ff',
    messagingSenderId: '145240505070',
    projectId: 'mealbuddy-e829c',
    databaseURL: 'https://mealbuddy-e829c-default-rtdb.firebaseio.com',
    storageBucket: 'mealbuddy-e829c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvlEXbUe0Nuu2tYaESNsOysB0BqVlzFM',
    appId: '1:145240505070:ios:85cf33c283b9e4d8d8d1ff',
    messagingSenderId: '145240505070',
    projectId: 'mealbuddy-e829c',
    databaseURL: 'https://mealbuddy-e829c-default-rtdb.firebaseio.com',
    storageBucket: 'mealbuddy-e829c.appspot.com',
    iosBundleId: 'com.example.mealRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvlEXbUe0Nuu2tYaESNsOysB0BqVlzFM',
    appId: '1:145240505070:ios:90f315b172e72e80d8d1ff',
    messagingSenderId: '145240505070',
    projectId: 'mealbuddy-e829c',
    databaseURL: 'https://mealbuddy-e829c-default-rtdb.firebaseio.com',
    storageBucket: 'mealbuddy-e829c.appspot.com',
    iosBundleId: 'com.example.mealRecommender.RunnerTests',
  );
}
